name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - jobtype: 1
          - jobtype: 2
          - jobtype: 3
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: sbt
    - if: ${{ matrix.jobtype == 1 }}
      shell: bash
      run: sbt -v "++2.13.x" library/test
    - if: ${{ matrix.jobtype == 2 }}
      shell: bash
      run: sbt -v "++2.12.x" test scripted
    - if: ${{ matrix.jobtype == 2 }}
      shell: bash
      run: sbt -v "++2.12.x" scalafmtCheckAll
